import hashlib
import hmac
import unittest
from pathlib import Path
from unittest.mock import patch

import test_sports_installment_payments as fixtures
from src.services.sports_installment_reconciliation import (
    find_installment_attempt, installment_withdrawal_allowed, reconcile_installment_order,
)


class InstallmentReconciliationTest(unittest.TestCase):
    setUp = fixtures.InstallmentPaymentsTest.setUp
    sale = fixtures.InstallmentPaymentsTest.sale
    setup_plan = fixtures.InstallmentPaymentsTest.setup_plan
    order = fixtures.InstallmentPaymentsTest.order
    charge = fixtures.InstallmentPaymentsTest.charge

    def setup_payments(self):
        self.setup_plan()
        self.db.conn.executescript(Path('supabase/migrations/20260813180000_sports_stock_reservations.sql').read_text().replace('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY','INTEGER PRIMARY KEY AUTOINCREMENT'))
        self.db.execute('ALTER TABLE sports_sale_item_details ADD COLUMN delivered_at TEXT')
        self.db.execute('ALTER TABLE sports_sale_item_details ADD COLUMN delivered_by INTEGER')
        self.db.conn.executescript(('CREATE TABLE' + Path('supabase/migrations/20260813190000_sports_fulfillment_history.sql').read_text().split('CREATE TABLE',1)[1]).replace('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY','INTEGER PRIMARY KEY AUTOINCREMENT'))
        self.db.execute('ALTER TABLE sports_product_variants ADD COLUMN stock INTEGER DEFAULT 5')
        item = self.db.execute('SELECT si.id,d.variant_id FROM sale_items si JOIN sports_sale_item_details d ON d.sale_item_id=si.id WHERE si.sale_id=?',(self.sale_id,)).fetchone()
        self.item_id=item['id']
        self.db.execute("INSERT INTO sports_stock_reservations(sale_item_id,variant_id,quantity,status) VALUES(?,?,?, 'reserved')",(self.item_id,item['variant_id'],1))
        self.db.commit()
        self.attempts=[]
        for number in (1,2,3):
            with patch('src.services.sports_installment_payments.create_pix_order',return_value=self.order(str(number))):
                self.attempts.append(self.charge(number))

    def event(self, number, status='processed', amount=None):
        a=self.attempts[number-1]
        return dict(id=a['mercado_pago_order_id'], external_reference=a['external_reference'],
                    status=status,status_detail='accredited',total_paid_amount=amount or f"{a['amount_cents']/100:.2f}",
                    transactions={'payments':[{'id':a['mercado_pago_payment_id']}]})

    def approve(self, number):
        return reconcile_installment_order(self.db,self.event(number))

    def state(self):
        return (dict(self.db.execute('SELECT * FROM sales WHERE id=?',(self.sale_id,)).fetchone()),
                dict(self.db.execute('SELECT * FROM sports_installment_plans WHERE sale_id=?',(self.sale_id,)).fetchone()))

    def test_first_unlocks_without_full_payment(self):
        self.setup_payments(); self.approve(1)
        sale,plan=self.state()
        self.assertTrue(installment_withdrawal_allowed(self.db,self.sale_id))
        self.assertEqual((sale['paid'],sale['payment_status'],plan['status']),(0,'pending','active'))
        self.assertIsNotNone(plan['first_installment_paid_at'])
        self.assertEqual(self.db.execute('SELECT status FROM sports_stock_reservations').fetchone()[0],'consumed')

    def test_only_second_blocked(self):
        self.setup_payments(); self.approve(2)
        self.assertFalse(installment_withdrawal_allowed(self.db,self.sale_id))
        self.assertEqual(self.state()[0]['paid'],0)

    def test_only_third_blocked(self):
        self.setup_payments(); self.approve(3)
        self.assertFalse(installment_withdrawal_allowed(self.db,self.sale_id))
        self.assertEqual(self.state()[0]['paid'],0)

    def test_second_and_third_blocked(self):
        self.setup_payments(); self.approve(2); self.approve(3)
        self.assertFalse(installment_withdrawal_allowed(self.db,self.sale_id))
        self.assertEqual((self.state()[0]['paid'],self.state()[1]['status']),(0,'pending'))

    def test_first_and_second_unpaid_but_unlocked(self):
        self.setup_payments(); self.approve(1); self.approve(2)
        self.assertTrue(installment_withdrawal_allowed(self.db,self.sale_id))
        self.assertEqual(self.state()[0]['paid'],0)

    def test_three_payments_settle_exact_total(self):
        self.setup_payments()
        for number in (1,2,3): self.approve(number)
        sale,plan=self.state()
        self.assertEqual((sale['paid'],sale['payment_status'],plan['status']),(1,'approved','paid'))
        self.assertIsNotNone(plan['fully_paid_at'])
        self.assertEqual(self.db.execute("SELECT SUM(amount_cents) FROM sports_installments WHERE status='paid'").fetchone()[0],sale['total_cents'])

    def test_reverse_sequence_converges(self):
        self.setup_payments()
        for number in (3,2,1): self.approve(number)
        self.assertEqual((self.state()[0]['paid'],self.state()[1]['status']),(1,'paid'))
        self.assertTrue(installment_withdrawal_allowed(self.db,self.sale_id))

    def test_duplicate_and_delayed_failure_preserve_all_timestamps(self):
        self.setup_payments(); self.approve(1)
        tables=('sales','sports_installments','sports_installment_plans','sports_installment_payment_attempts','sports_stock_reservations')
        before={t:[tuple(r) for r in self.db.execute(f'SELECT * FROM {t}').fetchall()] for t in tables}
        self.approve(1)
        reconcile_installment_order(self.db,self.event(1,'expired'))
        after={t:[tuple(r) for r in self.db.execute(f'SELECT * FROM {t}').fetchall()] for t in tables}
        self.assertEqual(before,after)

    def test_wrong_or_fractional_amount_rejected_atomically(self):
        self.setup_payments()
        for amount in ('100.00','33.331','NaN',None):
            event=self.event(1); event['total_paid_amount']=amount
            with self.subTest(amount=amount),self.assertRaises(ValueError):
                reconcile_installment_order(self.db,event)
        self.assertEqual(self.db.execute("SELECT COUNT(*) FROM sports_installments WHERE status='paid'").fetchone()[0],0)
        self.assertEqual(self.state()[1]['status'],'pending')

    def test_old_attempt_approval_does_not_pay_twice(self):
        self.setup_payments()
        old=self.attempts[0]
        self.db.execute("UPDATE sports_installment_payment_attempts SET status='expired' WHERE id=?",(old['id'],)); self.db.commit()
        with patch('src.services.sports_installment_payments.create_pix_order',return_value=self.order('new')):
            newer=self.charge(1)
        self.attempts[0]=newer; self.approve(1)
        before=self.state()
        self.attempts[0]=old; self.approve(1)
        self.assertEqual(self.state(),before)
        self.assertEqual(self.db.execute("SELECT COUNT(*) FROM sports_installments WHERE status='paid'").fetchone()[0],1)
        self.assertEqual(self.db.execute("SELECT COUNT(*) FROM sports_installment_payment_attempts WHERE status='approved'").fetchone()[0],2)

    def test_later_failures_do_not_cancel_or_restore_stock(self):
        from src.routes.sales import apply_mercadopago_status, restore_reserved_stock
        self.setup_payments(); self.approve(1)
        for number,status in ((2,'failed'),(3,'expired')):
            reconcile_installment_order(self.db,self.event(number,status))
        sale,plan=self.state()
        restore_reserved_stock(self.db,self.sale_id)
        apply_mercadopago_status(self.db,sale,{'status':'failed'})
        self.assertEqual(self.state(),(sale,plan))
        self.assertEqual(self.db.execute('SELECT stock FROM sports_product_variants').fetchone()[0],5)
        self.assertTrue(installment_withdrawal_allowed(self.db,self.sale_id))

    def test_conflicting_identifiers_rejected(self):
        self.setup_payments()
        event=self.event(1); event['external_reference']=self.attempts[1]['external_reference']
        with self.assertRaises(ValueError): find_installment_attempt(self.db,event)

    def test_creating_timeout_reconciled_by_reference(self):
        self.setup_payments()
        self.db.execute("UPDATE sports_installment_payment_attempts SET status='creating',mercado_pago_order_id=NULL,mercado_pago_payment_id=NULL WHERE id=?",(self.attempts[0]['id'],)); self.db.commit()
        self.approve(1)
        row=self.db.execute('SELECT * FROM sports_installment_payment_attempts WHERE id=?',(self.attempts[0]['id'],)).fetchone()
        self.assertEqual((row['status'],row['mercado_pago_order_id']),('approved','ORD-1'))

    def test_partial_withdrawal_and_restoration_keep_audit(self):
        from app import app
        from flask import g
        from src.routes.sales import deliver_order, restore_delivered_order
        self.setup_payments()
        self.db.execute('UPDATE sale_items SET quantity=2,unit_price_cents=5000 WHERE id=?',(self.item_id,))
        user=self.db.execute("INSERT INTO users(username,name,password_hash,role) VALUES('delivery','Admin','hash','manager')").lastrowid
        self.db.commit()
        # A stray ready flag must not unlock installments 2/3 alone.
        self.db.execute('UPDATE sales SET ready_for_delivery=1 WHERE id=?',(self.sale_id,)); self.db.commit()
        with app.test_request_context(json={'sale_item_id':self.item_id,'quantity':1}),patch('src.routes.sales.get_db',return_value=self.db):
            g.user={'id':user}
            self.assertEqual(deliver_order.__wrapped__(self.sale_id)[1],409)
        self.approve(1)
        with app.test_request_context(json={'sale_item_id':self.item_id,'quantity':1}),patch('src.routes.sales.get_db',return_value=self.db):
            g.user={'id':user}
            response=deliver_order.__wrapped__(self.sale_id)
            self.assertTrue(response.get_json()['partial'])
        self.assertEqual(self.db.execute('SELECT quantity FROM sale_item_deliveries').fetchone()[0],1)
        self.assertEqual(self.db.execute('SELECT COUNT(*) FROM sale_delivery_operations').fetchone()[0],1)
        with app.test_request_context(json={'reason':'Retirada registrada incorretamente'}),patch('src.routes.sales.get_db',return_value=self.db):
            g.user={'id':user}
            self.assertTrue(restore_delivered_order.__wrapped__(self.sale_id).get_json()['ok'])
        self.assertEqual(self.db.execute('SELECT quantity FROM sale_item_delivery_restorations').fetchone()[0],1)
        self.assertEqual(self.state()[0]['paid'],0)

    def test_sports_fulfillment_accepts_first_payment(self):
        from app import app
        from flask import g
        from src.routes.sales import update_sports_fulfillment
        self.setup_payments()
        user=self.db.execute("INSERT INTO users(username,name,password_hash,role) VALUES('sports','Admin','hash','manager')").lastrowid
        self.db.commit()
        self.approve(1)
        for target in ('delivered',):
            with app.test_request_context(json={'to_status':target}),patch('src.routes.sales.get_db',return_value=self.db):
                g.user={'id':user}
                response=update_sports_fulfillment.__wrapped__(self.item_id)
                self.assertTrue(response.get_json()['ok'])
        self.assertEqual(self.db.execute('SELECT COUNT(*) FROM sports_order_status_history').fetchone()[0],1)
        self.assertEqual(self.state()[0]['paid'],0)

    def test_webhook_routes_using_authenticated_provider_order(self):
        from app import app
        self.setup_payments()
        saved=dict(app.config); self.addCleanup(lambda:app.config.update(saved))
        app.config.update(TESTING=True,DATABASE=self.db.conn.execute('PRAGMA database_list').fetchone()[2],DATABASE_URL=None,APP_ENV='local',EXTERNAL_PAYMENTS_ENABLED=True,MERCADOPAGO_ACCESS_TOKEN='fake',MERCADOPAGO_WEBHOOK_SECRET='secret')
        event=self.event(1)
        stamp='12345'; request_id='phase3'
        signed=f"id:ord-1;request-id:{request_id};ts:{stamp};"
        digest=hmac.new(b'secret',signed.encode(),hashlib.sha256).hexdigest()
        with patch('src.routes.sales.get_order',return_value=event) as provider,patch('src.routes.sales.apply_mercadopago_status') as legacy:
            response=app.test_client().post('/webhooks/mercadopago',json={'data':{'id':'ORD-1','external_reference':event['external_reference'],'status':'failed'}},headers={'X-Request-Id':request_id,'X-Signature':f'ts={stamp},v1={digest}'})
        self.assertEqual(response.status_code,200)
        provider.assert_called_once(); legacy.assert_not_called()
        self.assertTrue(installment_withdrawal_allowed(self.db,self.sale_id))


if __name__=='__main__': unittest.main()
