-- Phase D: per-item sports fulfillment delivery and append-only history.
ALTER TABLE sports_sale_item_details
    ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS delivered_by BIGINT REFERENCES users(id);

CREATE TABLE IF NOT EXISTS sports_order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_item_id BIGINT NOT NULL REFERENCES sale_items(id) ON DELETE CASCADE,
    from_status TEXT NOT NULL CHECK(from_status IN ('reserved','requested','in_production','available','delivered')),
    to_status TEXT NOT NULL CHECK(to_status IN ('reserved','requested','in_production','available','delivered')),
    changed_by BIGINT REFERENCES users(id),
    notes TEXT NOT NULL DEFAULT '',
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sports_order_history_item_time
    ON sports_order_status_history(sale_item_id,changed_at,id);
