-- Phase B: dedicated Material Esportivo catalog and size-level inventory.
CREATE TABLE IF NOT EXISTS sports_material_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sports_material_types(code,name,sort_order) VALUES
('game_kit','Kit de jogo',10),
('sweatshirt_kit','Kit moletom',20),
('tracksuit_kit','Kit agasalho',30),
('shirt','Camisa avulsa',40),
('shorts','Calção avulso',50),
('socks','Meião avulso',60),
('polo','Camisa polo',70),
('commemorative_coin','Moeda comemorativa',80)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS sports_product_config (
    product_id BIGINT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    type_id BIGINT NOT NULL REFERENCES sports_material_types(id),
    allow_custom_name BOOLEAN NOT NULL DEFAULT FALSE,
    allow_custom_number BOOLEAN NOT NULL DEFAULT FALSE,
    allow_backorder BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sports_product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    size TEXT NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0 CHECK(stock >= 0),
    min_stock INTEGER NOT NULL DEFAULT 0 CHECK(min_stock >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id,size)
);

CREATE INDEX IF NOT EXISTS idx_sports_types_active
    ON sports_material_types(active,sort_order,name);
CREATE INDEX IF NOT EXISTS idx_sports_variants_product
    ON sports_product_variants(product_id,active,size);
CREATE INDEX IF NOT EXISTS idx_sports_variants_low_stock
    ON sports_product_variants(active,stock,min_stock);
