-- Phase C2: persistent, idempotent Pix reservations for sports variants.
CREATE TABLE IF NOT EXISTS sports_stock_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_item_id BIGINT NOT NULL UNIQUE REFERENCES sale_items(id) ON DELETE CASCADE,
    variant_id BIGINT NOT NULL REFERENCES sports_product_variants(id),
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    status TEXT NOT NULL DEFAULT 'reserved' CHECK(status IN ('reserved','consumed','released')),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sports_reservations_status_expiry ON sports_stock_reservations(status,expires_at);
CREATE INDEX IF NOT EXISTS idx_sports_reservations_variant ON sports_stock_reservations(variant_id);
