ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS last_push_at TIMESTAMP;
ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS last_push_status TEXT NOT NULL DEFAULT 'never';
ALTER TABLE push_subscriptions ADD COLUMN IF NOT EXISTS last_push_error TEXT DEFAULT '';
ALTER TABLE push_inbox ADD COLUMN IF NOT EXISTS body_html TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS expiry_date TEXT DEFAULT '';

CREATE TABLE IF NOT EXISTS tribute_settings (
    id INTEGER PRIMARY KEY CHECK(id=1), enabled INTEGER NOT NULL DEFAULT 1,
    title TEXT NOT NULL DEFAULT 'PELADEIROS GPCTA', body TEXT NOT NULL DEFAULT '🗣️ VEEENHAAAMMM...',
    body_html TEXT NOT NULL DEFAULT '🗣️ VEEENHAAAMMM...', image_data TEXT NOT NULL DEFAULT '',
    updated_by INTEGER REFERENCES users(id), updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tribute_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
CREATE TABLE IF NOT EXISTS tribute_schedules (
    weekday INTEGER PRIMARY KEY CHECK(weekday BETWEEN 0 AND 6), enabled INTEGER NOT NULL DEFAULT 0,
    hour INTEGER NOT NULL DEFAULT 12 CHECK(hour BETWEEN 0 AND 23), updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tribute_schedules(weekday,enabled,hour) VALUES(2,1,17) ON CONFLICT(weekday) DO NOTHING;
INSERT INTO tribute_schedules(weekday,enabled,hour) VALUES(5,1,15) ON CONFLICT(weekday) DO NOTHING;
